//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImyHelloWorldService")]
public interface ImyHelloWorldService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImyHelloWorldService/HelloWorld", ReplyAction="http://tempuri.org/ImyHelloWorldService/HelloWorldResponse")]
    string HelloWorld(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImyHelloWorldService/HelloWorld", ReplyAction="http://tempuri.org/ImyHelloWorldService/HelloWorldResponse")]
    System.Threading.Tasks.Task<string> HelloWorldAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ImyHelloWorldServiceChannel : ImyHelloWorldService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ImyHelloWorldServiceClient : System.ServiceModel.ClientBase<ImyHelloWorldService>, ImyHelloWorldService
{
    
    public ImyHelloWorldServiceClient()
    {
    }
    
    public ImyHelloWorldServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ImyHelloWorldServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImyHelloWorldServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImyHelloWorldServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string HelloWorld(string name)
    {
        return base.Channel.HelloWorld(name);
    }
    
    public System.Threading.Tasks.Task<string> HelloWorldAsync(string name)
    {
        return base.Channel.HelloWorldAsync(name);
    }
}
